/* Browser adaptation inspired by BlagojeBlagojevic/wrogue (README states MIT). */
(()=>{'use strict';const C=document.getElementById('game'),g=C.getContext('2d'),W=52,H=30,T=22,OX=28,OY=28;
let s;
const R=n=>Math.floor(Math.random()*n),dirs=[[0,-1],[0,1],[-1,0],[1,0],[-1,-1],[1,-1],[-1,1],[1,1]];
function room(x,y,w,h){return{x,y,w,h,cx:x+(w>>1),cy:y+(h>>1)}}
function newLevel(reset=true){let map=Array.from({length:H},()=>Array(W).fill('#')),rooms=[];for(let n=0;n<22;n++){let r=room(2+R(W-12),2+R(H-9),5+R(8),4+R(5));if(rooms.some(q=>r.x<q.x+q.w+1&&r.x+r.w+1>q.x&&r.y<q.y+q.h+1&&r.y+r.h+1>q.y))continue;for(let y=r.y;y<r.y+r.h;y++)for(let x=r.x;x<r.x+r.w;x++)map[y][x]='.';if(rooms.length){let q=rooms.at(-1),x=q.cx,y=q.cy;while(x!==r.cx){map[y][x]='.';x+=Math.sign(r.cx-x)}while(y!==r.cy){map[y][x]='.';y+=Math.sign(r.cy-y)}}rooms.push(r)}let a=rooms[0],z=rooms.at(-1);map[z.cy][z.cx]='>';let p=reset?{x:a.cx,y:a.cy,hp:40,max:40,st:20,hunger:120,atk:5,def:1,level:1,xp:0,gold:0,inv:[]}:{...s.p,x:a.cx,y:a.cy};s={map,rooms,p,level:reset?1:s.level+1,mon:[],items:[],log:reset?['You enter the forgotten halls.']:['You descend deeper.'],over:false,won:false};let types=[['z','Zombie',12,3],['g','Ghoul',9,5],['a','Acolyte',7,4],['o','Orc',16,4]];for(let i=0;i<7+s.level*2;i++){let q=rooms[1+R(Math.max(1,rooms.length-1))],t=types[R(Math.min(types.length,2+Math.floor(s.level/2)))];s.mon.push({x:q.cx+R(3)-1,y:q.cy+R(3)-1,ch:t[0],name:t[1],hp:t[2]+s.level*2,atk:t[3]+Math.floor(s.level/2)})}for(let i=0;i<5;i++){let q=rooms[R(rooms.length)],it=R(4);s.items.push({x:q.cx+R(3)-1,y:q.cy+R(3)-1,type:it,name:['healing potion','iron sword','ration','gold pouch'][it]})}}
function walkable(x,y){return x>=0&&y>=0&&x<W&&y<H&&s.map[y][x]!=='#'}function at(a,x,y){return a.find(v=>v.x===x&&v.y===y)}function msg(t){s.log.unshift(t);s.log=s.log.slice(0,7)}
function attack(m){let d=Math.max(1,s.p.atk+R(4)-1);m.hp-=d;msg(`You strike ${m.name} for ${d}.`);if(m.hp<=0){s.p.xp+=5;s.p.gold+=R(4);msg(`${m.name} falls.`);s.mon=s.mon.filter(x=>x!==m);if(s.p.xp>=s.p.level*15){s.p.level++;s.p.xp=0;s.p.max+=5;s.p.hp=s.p.max;s.p.atk++;msg('You grow stronger.')}}}
function enemyTurn(){for(const m of [...s.mon]){let dx=Math.sign(s.p.x-m.x),dy=Math.sign(s.p.y-m.y),dist=Math.max(Math.abs(s.p.x-m.x),Math.abs(s.p.y-m.y));if(dist<=1){let d=Math.max(1,m.atk+R(3)-s.p.def);s.p.hp-=d;msg(`${m.name} hits you for ${d}.`)}else if(dist<10){let nx=m.x+dx,ny=m.y+dy;if(walkable(nx,ny)&&!at(s.mon,nx,ny)&&(nx!==s.p.x||ny!==s.p.y)){m.x=nx;m.y=ny}}}s.p.hunger--;if(s.p.hunger<=0){s.p.hp--;if(s.p.hunger%8===0)msg('Hunger drains your strength.')}s.p.st=Math.min(20,s.p.st+1);if(s.p.hp<=0){s.over=true;msg('You died in the dungeon.')}}
function move(dx,dy){if(s.over)return;let nx=s.p.x+dx,ny=s.p.y+dy,m=at(s.mon,nx,ny);if(m)attack(m);else if(walkable(nx,ny)){s.p.x=nx;s.p.y=ny}s.p.st=Math.max(0,s.p.st-1);enemyTurn()}
function pickup(){let it=at(s.items,s.p.x,s.p.y);if(!it)return msg('Nothing here to pick up.');s.items=s.items.filter(x=>x!==it);if(it.type===3){let n=8+R(18);s.p.gold+=n;msg(`You collect ${n} gold.`)}else{s.p.inv.push(it);msg(`Picked up ${it.name}.`)}}
function use(){if(!s.p.inv.length)return msg('Your pack is empty.');let it=s.p.inv.shift();if(it.type===0){s.p.hp=Math.min(s.p.max,s.p.hp+16);msg('The potion restores health.')}if(it.type===1){s.p.atk+=2;msg('You equip the iron sword.')}if(it.type===2){s.p.hunger=Math.min(120,s.p.hunger+60);msg('You eat the ration.')}}
function key(e){let k=e.key.toLowerCase();if(s.over&&k==='enter'){newLevel(true);return}let map={w:[0,-1],arrowup:[0,-1],s:[0,1],arrowdown:[0,1],a:[-1,0],arrowleft:[-1,0],d:[1,0],arrowright:[1,0],q:[-1,-1],e:[1,-1],z:[-1,1],c:[1,1]};if(map[k]){e.preventDefault();move(...map[k])}else if(k===' '){e.preventDefault();enemyTurn()}else if(k==='p')pickup();else if(k==='u')use();else if(k==='>'||k==='enter'){if(s.map[s.p.y][s.p.x]==='>')newLevel(false);else msg('Find the stairs first.')}draw()}
function draw(){g.fillStyle='#080a0b';g.fillRect(0,0,C.width,C.height);for(let y=0;y<H;y++)for(let x=0;x<W;x++){let px=OX+x*T,py=OY+y*T,ch=s.map[y][x];g.fillStyle=ch==='#'?'#151a1b':'#272b28';g.fillRect(px,py,T-1,T-1);if(ch==='>'){g.fillStyle='#c9a95b';g.font='18px monospace';g.fillText('>',px+5,py+17)}}for(const it of s.items){g.fillStyle=['#b54742','#a9a17b','#9a7548','#d0b65d'][it.type];g.fillRect(OX+it.x*T+6,OY+it.y*T+6,10,10)}for(const m of s.mon){g.fillStyle={z:'#6f765a',g:'#8a5648',a:'#755d87',o:'#708052'}[m.ch];g.fillRect(OX+m.x*T+3,OY+m.y*T+3,16,16);g.fillStyle='#111';g.font='bold 13px monospace';g.fillText(m.ch.toUpperCase(),OX+m.x*T+7,OY+m.y*T+16)}g.fillStyle='#e1d19b';g.fillRect(OX+s.p.x*T+2,OY+s.p.y*T+2,18,18);g.fillStyle='#161616';g.font='bold 15px monospace';g.fillText('@',OX+s.p.x*T+5,OY+s.p.y*T+17);
let bx=OX+W*T+22;g.fillStyle='#121616';g.fillRect(bx,OY,190,660);g.fillStyle='#d7d1b5';g.font='bold 18px monospace';g.fillText(`WROGUE JS`,bx+15,OY+28);g.font='14px monospace';g.fillText(`DEPTH ${s.level}`,bx+15,OY+58);g.fillText(`HP ${s.p.hp}/${s.p.max}`,bx+15,OY+92);g.fillText(`STAMINA ${s.p.st}/20`,bx+15,OY+118);g.fillText(`HUNGER ${s.p.hunger}`,bx+15,OY+144);g.fillText(`ATK ${s.p.atk}  DEF ${s.p.def}`,bx+15,OY+170);g.fillText(`GOLD ${s.p.gold}`,bx+15,OY+196);g.fillText(`LEVEL ${s.p.level}`,bx+15,OY+222);g.fillStyle='#918d79';g.fillText('PACK',bx+15,OY+260);s.p.inv.slice(0,7).forEach((i,n)=>g.fillText(`${n+1}. ${i.name}`,bx+15,OY+286+n*22));g.fillStyle='#b8b199';g.fillText('MESSAGES',bx+15,OY+468);s.log.forEach((m,n)=>{for(let i=0;i<m.length;i+=22)g.fillText(m.slice(i,i+22),bx+15,OY+494+n*37+(i/22)*16)});if(s.over){g.fillStyle='#050606dd';g.fillRect(0,0,C.width,C.height);g.fillStyle='#c9bda3';g.font='bold 58px monospace';g.textAlign='center';g.fillText('YOU DIED',C.width/2,300);g.font='18px monospace';g.fillText('Press Enter to begin again',C.width/2,350);g.textAlign='left'}g.fillStyle='#777';g.font='12px monospace';g.fillText('WASD/ARROWS MOVE · Q/E/Z/C DIAGONAL · P PICK UP · U USE · ENTER STAIRS · SPACE WAIT',28,708)}
addEventListener('keydown',key);newLevel(true);draw();})();
